### ISSUE TITLE
Module is not installing

### ISSUE THREAD

**Issue by murtuza-kolasavala** [weserv/rate-limit-nginx-module#4]
I am trying to install this module in existing nginx. Followed the steps and tried configuring using below command.

`./configure --with-compat --add-dynamic-module=rate-limit-nginx-module --prefix=/etc/nginx`

Module ngx_http_rate_limit_module.so is getting installed in /etc/nginx/modules but when i add directive `rate_limit_pass redis;` it is giving below error.

`nginx: [emerg] unknown directive "rate_limit_pass" in /etc/nginx/conf.d/file.conf:28`

Tried loading module in nginx.conf `load_module modules/ngx_http_rate_limit_module.so;`

nginx: [emerg] module "/etc/nginx/modules/ngx_http_rate_limit_module.so" is not binary compatible in /etc/nginx/nginx.conf:3

**Comment by kleisauke** [comment]
Hi @murtuza-kolasavala,

For dynamic modules in nginx, the `load_module <PATH>/ngx_http_rate_limit_module.so` directive is mandatory. So, the first error is expected.

The second error means that you'll need:
- the exact same version of nginx's source code for compiling the dynamic module.
- nginx itself must be compiled with `-with-compat`, if not the same compilation flags and compiler must be used.

Both can be verified with `nginx -V`.

**Comment by murtuza-kolasavala** [comment]
Thanks This issue is resolved, I added module with below command and it worked.

`nginx -V 2>&1 | egrep  "^configure" | cut -d: -f2 > /tmp/nginx_build_options.txt
sh -c "./configure $(cat /tmp/nginx_build_options.txt) --add-dynamic-module=`
